/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.kcent;

import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author minja
 */
public class MainWindow extends javax.swing.JFrame {

    DefaultTableModel model;
    
    Double prihodi;
    Double rashodi;
    
    public MainWindow() {
        initComponents();
        model = (DefaultTableModel) tb.getModel();
        prihodi = 0.;
        rashodi = 0.;
        tf_prihodi.setText(prihodi.toString());
        tf_rashodi.setText(rashodi.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogRezervacija = new javax.swing.JDialog();
        bt_res_quit = new javax.swing.JButton();
        bt_res_ok = new javax.swing.JButton();
        sp_res = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        sl_res = new javax.swing.JSlider();
        dialogManifestacija = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf1_man = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf2_man = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb1_man = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rb1_man = new javax.swing.JRadioButton();
        rb2_man = new javax.swing.JRadioButton();
        rb3_man = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        sp1_man = new javax.swing.JSpinner();
        sl1_man = new javax.swing.JSlider();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_prihodi = new javax.swing.JTextField();
        tf_rashodi = new javax.swing.JTextField();
        bt_quit = new javax.swing.JButton();
        bt_new = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        bt_del = new javax.swing.JButton();
        bt_res = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();

        dialogRezervacija.setTitle("Rezervacija");
        dialogRezervacija.setMinimumSize(new java.awt.Dimension(300, 200));

        bt_res_quit.setText("Odustani");
        bt_res_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_res_quitActionPerformed(evt);
            }
        });

        bt_res_ok.setText("OK");
        bt_res_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_res_okActionPerformed(evt);
            }
        });

        sp_res.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp_resStateChanged(evt);
            }
        });

        jLabel3.setText("Broj mesta za rezervaciju:");

        sl_res.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sl_resStateChanged(evt);
            }
        });

        javax.swing.GroupLayout dialogRezervacijaLayout = new javax.swing.GroupLayout(dialogRezervacija.getContentPane());
        dialogRezervacija.getContentPane().setLayout(dialogRezervacijaLayout);
        dialogRezervacijaLayout.setHorizontalGroup(
            dialogRezervacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRezervacijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogRezervacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sl_res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRezervacijaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_res_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_res_quit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRezervacijaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp_res, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dialogRezervacijaLayout.setVerticalGroup(
            dialogRezervacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRezervacijaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dialogRezervacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addComponent(sl_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(dialogRezervacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_res_quit)
                    .addComponent(bt_res_ok))
                .addContainerGap())
        );

        dialogManifestacija.setTitle("Manifestacija");
        dialogManifestacija.setMinimumSize(new java.awt.Dimension(400, 400));
        dialogManifestacija.setPreferredSize(new java.awt.Dimension(400, 400));

        jButton1.setText("Odustani");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Naziv manfiestacija:");

        jLabel5.setText("Organizator manifestacije:");

        jLabel6.setText("Tip manifestacije:");

        cb1_man.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Koncert", "Izložba", "Predstava", "Film. projekcija" }));

        jLabel7.setText("Sala za rezervaciju:");

        buttonGroup1.add(rb1_man);
        rb1_man.setSelected(true);
        rb1_man.setText("Mala sala");
        rb1_man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1_manActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2_man);
        rb2_man.setText("Srednja sala");
        rb2_man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2_manActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb3_man);
        rb3_man.setText("Velika sala");
        rb3_man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3_manActionPerformed(evt);
            }
        });

        jLabel8.setText("Ukupan broj mesta:");

        sp1_man.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        sp1_man.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp1_manStateChanged(evt);
            }
        });

        sl1_man.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sl1_manStateChanged(evt);
            }
        });

        javax.swing.GroupLayout dialogManifestacijaLayout = new javax.swing.GroupLayout(dialogManifestacija.getContentPane());
        dialogManifestacija.getContentPane().setLayout(dialogManifestacijaLayout);
        dialogManifestacijaLayout.setHorizontalGroup(
            dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(dialogManifestacijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogManifestacijaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogManifestacijaLayout.createSequentialGroup()
                        .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogManifestacijaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(63, 63, 63)
                                .addComponent(sp1_man))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogManifestacijaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(cb1_man, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogManifestacijaLayout.createSequentialGroup()
                                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf1_man)
                                    .addComponent(tf2_man, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
                        .addGap(9, 9, 9))
                    .addGroup(dialogManifestacijaLayout.createSequentialGroup()
                        .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(dialogManifestacijaLayout.createSequentialGroup()
                                .addComponent(rb1_man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb2_man)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb3_man)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sl1_man, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogManifestacijaLayout.setVerticalGroup(
            dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogManifestacijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1_man, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf2_man, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb1_man, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1_man)
                    .addComponent(rb2_man)
                    .addComponent(rb3_man))
                .addGap(18, 18, 18)
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sp1_man, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(sl1_man, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(dialogManifestacijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kulturni Centar");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ukupni prihodi:");

        jLabel2.setText("Troškovi održavanja:");

        tf_prihodi.setFocusable(false);

        tf_rashodi.setFocusable(false);

        bt_quit.setText("Kraj");
        bt_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitActionPerformed(evt);
            }
        });

        bt_new.setText("Novi događaj");
        bt_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newActionPerformed(evt);
            }
        });

        bt_edit.setText("Izmena");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_del.setText("Obriši");
        bt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delActionPerformed(evt);
            }
        });

        bt_res.setText("Rezervacija");
        bt_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_del, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_res, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_rashodi)
                            .addComponent(tf_prihodi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_prihodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_rashodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_quit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_new)
                            .addComponent(bt_res))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_edit)
                        .addGap(18, 18, 18)
                        .addComponent(bt_del)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv", "Organizator", "Tip Manifestacije", "Sala", "Broj Mesta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        if(tb.getSelectedRow() > -1){
            String manifestacija = model.getValueAt(tb.getSelectedRow(), 0).toString();
            String organizator = model.getValueAt(tb.getSelectedRow(), 1).toString();
            String tip = model.getValueAt(tb.getSelectedRow(), 2).toString();
            String sala = model.getValueAt(tb.getSelectedRow(), 3).toString();

            if(sala== "Mala"){
                rb1_man.setSelected(true);
                ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(20);
                ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
                sl1_man.setMaximum(20);
                sl1_man.setMinimum(0);
            }
            if(sala== "Srednja"){
                rb2_man.setSelected(true);
                ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(50);
                ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
                sl1_man.setMaximum(50);
                sl1_man.setMinimum(0);
            }
            if(sala== "Velika"){
                rb3_man.setSelected(true);
                ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(100);
                ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
                sl1_man.setMaximum(100);
                sl1_man.setMinimum(0);
            }

            Integer rb = (Integer) model.getValueAt(tb.getSelectedRow(), 4);
            
            tf1_man.setText(manifestacija);
            tf2_man.setText(organizator);
            
            cb1_man.setSelectedItem(tip);
            
            sp1_man.setValue(rb);
            sl1_man.setValue(rb);
            
            dialogManifestacija.setVisible(true);
        }
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resActionPerformed
        if(tb.getSelectedRow() > -1){
            Integer num = (Integer) model.getValueAt(tb.getSelectedRow(), 4);
            ((SpinnerNumberModel)sp_res.getModel()).setMaximum(num);
            ((SpinnerNumberModel)sp_res.getModel()).setMinimum(0);
            sl_res.setValue(0);
            sl_res.setMaximum(num);
            sl_res.setMinimum(0);
            dialogRezervacija.setVisible(true);
        }
    }//GEN-LAST:event_bt_resActionPerformed

    private void bt_res_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_res_quitActionPerformed
        dialogRezervacija.dispose();
    }//GEN-LAST:event_bt_res_quitActionPerformed

    private void bt_res_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_res_okActionPerformed
        dialogRezervacija.dispose();
        Integer num = sl_res.getValue();
        Integer old = (Integer) model.getValueAt(tb.getSelectedRow(), 4);
        model.setValueAt(old - num, tb.getSelectedRow(), 4);
    }//GEN-LAST:event_bt_res_okActionPerformed

    private void bt_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_quitActionPerformed

    private void bt_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_newActionPerformed
        tf1_man.setText("");
        tf2_man.setText("");
        cb1_man.setSelectedIndex(0);
        rb1_man.setSelected(true);
        rb2_man.setSelected(false);
        rb3_man.setSelected(false);
        sp1_man.setValue(0);
        ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(20);
        ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
        sl1_man.setValue(0);
        sl1_man.setMaximum(20);
        sl1_man.setMinimum(0);
        dialogManifestacija.setVisible(true);
    }//GEN-LAST:event_bt_newActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dialogManifestacija.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String manifestacija = tf1_man.getText();
        String organizator = tf2_man.getText();
        String tip = cb1_man.getSelectedItem().toString();
        String sala = "";
        
        Integer rb = sl1_man.getValue();
        
        if(rb1_man.isSelected())
        {
            sala= "Mala";
            prihodi += 105. * rb.doubleValue();
            rashodi += 1000.;
        }
        if(rb2_man.isSelected())
        {
            sala= "Srednja";
            prihodi += 55. * rb.doubleValue();
            rashodi += 2000.;
        }
        if(rb3_man.isSelected())
        {
            sala= "Velika";
            prihodi += 50. * rb.doubleValue();
            rashodi += 3000.;
        }
        
        model.addRow(new Object[] {manifestacija,organizator,tip,sala,rb});
        
        dialogManifestacija.dispose();
        
        tf_prihodi.setText(prihodi.toString());
        tf_rashodi.setText(rashodi.toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb1_manActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1_manActionPerformed
        ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(20);                          
         ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
        sl1_man.setValue(0);
        sl1_man.setMaximum(20);
        sl1_man.setMinimum(0);
    }//GEN-LAST:event_rb1_manActionPerformed

    private void rb2_manActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2_manActionPerformed
        ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(50);
        ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
        sl1_man.setValue(0);
        sl1_man.setMaximum(50);
        sl1_man.setMinimum(0);
    }//GEN-LAST:event_rb2_manActionPerformed

    private void rb3_manActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3_manActionPerformed
        ((SpinnerNumberModel)sp1_man.getModel()).setMaximum(100);
        ((SpinnerNumberModel)sp1_man.getModel()).setMinimum(0);
        sl1_man.setValue(0);
        sl1_man.setMaximum(100);
        sl1_man.setMinimum(0);
    }//GEN-LAST:event_rb3_manActionPerformed

    private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delActionPerformed
        if(tb.getSelectedRow() > -1)
            model.removeRow(tb.getSelectedRow());
    }//GEN-LAST:event_bt_delActionPerformed

    private void sp_resStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp_resStateChanged
        sl_res.setValue((Integer) sp_res.getValue());
    }//GEN-LAST:event_sp_resStateChanged

    private void sl_resStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sl_resStateChanged
        sp_res.setValue(sl_res.getValue());
    }//GEN-LAST:event_sl_resStateChanged

    private void sp1_manStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp1_manStateChanged
        sl1_man.setValue((Integer) sp1_man.getValue());
    }//GEN-LAST:event_sp1_manStateChanged

    private void sl1_manStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sl1_manStateChanged
        sp1_man.setValue(sl1_man.getValue());
    }//GEN-LAST:event_sl1_manStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_del;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_new;
    private javax.swing.JButton bt_quit;
    private javax.swing.JButton bt_res;
    private javax.swing.JButton bt_res_ok;
    private javax.swing.JButton bt_res_quit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb1_man;
    private javax.swing.JDialog dialogManifestacija;
    private javax.swing.JDialog dialogRezervacija;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb1_man;
    private javax.swing.JRadioButton rb2_man;
    private javax.swing.JRadioButton rb3_man;
    private javax.swing.JSlider sl1_man;
    private javax.swing.JSlider sl_res;
    private javax.swing.JSpinner sp1_man;
    private javax.swing.JSpinner sp_res;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tf1_man;
    private javax.swing.JTextField tf2_man;
    private javax.swing.JTextField tf_prihodi;
    private javax.swing.JTextField tf_rashodi;
    // End of variables declaration//GEN-END:variables
}
